<a href="https://colab.research.google.com/github/RawanZagh/Colab-Test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors in pytorch**
**bold text**
**tensors are important because it is the datastructure that suits GPU applications in colab**



**torch 1D tensor**

In [19]:
import torch

In [7]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

**torch 2D float tensor**

In [20]:
y = torch.tensor([[1,2,3],[1,2,3]], dtype = torch.float)
y

tensor([[1., 2., 3.],
        [1., 2., 3.]])

**torch of ones tensor of type int**

In [10]:
z = torch.ones(1,2,dtype=torch.int)
z

tensor([[1, 1]], dtype=torch.int32)

**torch of zeros tensor of type float**

In [11]:
w = torch.zeros(5,2,3,dtype = torch.float)
w

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

**torch of random numbers of type float**

In [12]:
M = torch.rand(3,4,2,dtype = torch.float)
M

tensor([[[0.0644, 0.2127],
         [0.9678, 0.3104],
         [0.7611, 0.5213],
         [0.6957, 0.8050]],

        [[0.1338, 0.8353],
         [0.0635, 0.5702],
         [0.1754, 0.4283],
         [0.7274, 0.7922]],

        [[0.1395, 0.3698],
         [0.4321, 0.3291],
         [0.9197, 0.4378],
         [0.0736, 0.8890]]])

In [13]:
print (y)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


**size of a tensor**

In [16]:
y.size()[1]

3

**reshape a tensor**

In [17]:
y.reshape(1,6)

tensor([[1., 2., 3., 1., 2., 3.]])

**reshape to 1D**
you can use the -1 as bellow or you can use squeeze function also:


```
# torch.squeeze(y.reshape(1,6))
```



In [18]:
y.reshape(-1)

tensor([1., 2., 3., 1., 2., 3.])

**To sum a tensor**

In [22]:
y.sum()
y

tensor([[1., 2., 3.],
        [1., 2., 3.]])

**sum all the columns in Y**

In [23]:
y.sum(0)

tensor([2., 4., 6.])

**max of y**

In [24]:
y.max()

tensor(3.)

In [25]:
torch.max(y)

tensor(3.)

In [31]:
values, indicies = torch.max(y,1)
print(values)
print(indicies)

tensor([3., 3.])
tensor([2, 2])


**retrive the items from a tensor**
when we retreive items from a tensor like y[:,0] it returns a tensor containning the chosen items. however if we want the items without including them in a tensor we can use the item function.

In [34]:
print(y)
print(y[0,0])
print(y[0,0].item())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
tensor(1.)
1.0


**Convert between tensors and numpy arrays**

In [35]:
y.numpy()

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [37]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
b = torch.from_numpy(a)
print(b)
a[0,1] = 3
print(a)
print(b)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 3]
 [3 4]]
tensor([[1, 3],
        [3, 4]])
